/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import model.FoodInventorySystem;
import access.Ingredientdao;
import model.Ingredient;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JTable;

/**
 *
 * @author imkir
 */
public class homeadmin extends javax.swing.JFrame {
private Ingredientdao ingredientDao = new Ingredientdao();


    /**
     * Creates new form FoodInventorySystem
     */
    public homeadmin() {
        initComponents();


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        ingtable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ingname = new javax.swing.JTextField();
        ingexpiry = new javax.swing.JFormattedTextField();
        addbtn = new javax.swing.JButton();
        updatebtn = new javax.swing.JButton();
        delbtn = new javax.swing.JButton();
        clearbtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jScrollPane3MouseDragged(evt);
            }
        });

        ingtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Expiry Date"
            }
        ));
        ingtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ingtableMouseClicked(evt);
            }
        });
        ingtable.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                ingtableComponentShown(evt);
            }
        });
        jScrollPane2.setViewportView(ingtable);

        jScrollPane3.setViewportView(jScrollPane2);

        jLabel1.setText("Name");

        jLabel2.setText("Expiry Date");

        ingname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingnameActionPerformed(evt);
            }
        });

        ingexpiry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingexpiryActionPerformed(evt);
            }
        });

        addbtn.setText("Add");
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });

        updatebtn.setText("Update");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });

        delbtn.setText("Delete");
        delbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delbtnActionPerformed(evt);
            }
        });

        clearbtn.setText("Clear");
        clearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbtnActionPerformed(evt);
            }
        });

        jLabel3.setText("Ingredient Added Successfully!!");

        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(144, 144, 144)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(ingname)
                            .addComponent(jLabel2)
                            .addComponent(ingexpiry)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addbtn)
                                .addGap(18, 18, 18)
                                .addComponent(updatebtn)
                                .addGap(30, 30, 30)
                                .addComponent(delbtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                                .addComponent(clearbtn)))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addComponent(jLabel3))
                .addContainerGap(430, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(201, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(ingname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(ingexpiry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addbtn)
                            .addComponent(updatebtn)
                            .addComponent(delbtn)
                            .addComponent(clearbtn)
                            .addComponent(jButton1))
                        .addGap(27, 27, 27)
                        .addComponent(jLabel3))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(172, 172, 172))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
        // TODO add your handling code here:                                                                                                                   
                                                                                                                   
    int selectedRow = ingtable.getSelectedRow();
    if (selectedRow != -1) {
        try {
            int id = Integer.parseInt(ingtable.getValueAt(selectedRow, 0).toString());
            String name = ingname.getText();
            String expiryText = ingexpiry.getText();
            if (expiryText != null && !expiryText.isEmpty()) {
                // Assuming the date is in the format yyyy-MM-dd
                SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                Date expiryDate = dateFormat.parse(expiryText);
                Ingredient ingredient = new Ingredient(id, name, expiryDate);
                ingredientDao.updateIngredient(ingredient);
                jLabel3.setText("Ingredient Updated Successfully!!");
            } 
            else {
                jLabel3.setText("Please enter a valid expiry date.");
            }
        } catch (NumberFormatException e) {
            jLabel3.setText("Failed to parse ingredient ID: " + e.getMessage());
        } catch (ParseException e) {
            jLabel3.setText("Failed to parse expiry date: " + e.getMessage());
        } catch (Exception e) {
            jLabel3.setText("Failed to Update Ingredient: " + e.getMessage());
        }
    } else {
        jLabel3.setText("Please select an ingredient to update.");
    }
          

    }//GEN-LAST:event_updatebtnActionPerformed

    private void clearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbtnActionPerformed
        // TODO add your handling code here:                                      
    ingname.setText("");
    ingexpiry.setText("");
    jLabel3.setText("Fields Cleared!!");

    }//GEN-LAST:event_clearbtnActionPerformed

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
//        // TODO add your handling code here:                                 
    String name = ingname.getText();
//    String expiry = IngExpiry.getText(); // Format should be validated before conversion
//    try {
//        Date expiryDate = Date.valueOf(expiry); // Converts string to java.sql.Date
//        Ingredient ingredient = new Ingredient(0, name, expiryDate);
//        ingredientDao.addIngredient(ingredient);
//        jLabel3.setText("Ingredient Added Successfully!!");
//    } catch (Exception e) {
//        jLabel3.setText("Failed to Add Ingredient: " + e.getMessage());
//    
//}  

//  String date="2-3-2024";
 
        // Example string containing dates
  String dateString = ingexpiry.getText();

//        // Tokenize the string by splitting it using spaces
//        String[] dateTokens = dateString.split("\\s+");
//
//        // Specify the format of the dates in the string
//        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
//
//        // Create a list to store Date objects
//        List<Date> dateObjects = new ArrayList<>();
//
//        // Parse each token into a Date object
//       for (String token : dateTokens) {
//           try {
//                Date date = dateFormat.parse(token);
//               dateObjects.add(date);
//           } catch (ParseException e) {
//                e.printStackTrace();
//            }
//        }
//
////        Print the Date objects
//        for (Date date : dateObjects) {
//            System.out.println(date);
//        }

        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        Date date;
        try {
            date = dateFormat.parse(dateString);
            // Now 'date' contains the parsed date object
            System.out.println("Parsed Date: " + date);
            boolean result = ingredientDao.addIngredient(new Ingredient(name,  date));
            if(result){
                List<Ingredient> ingrediantsList = Ingredientdao.getAllIngredients();
//                DefaultTableModel tableModel = (DefaultTableModel) ingtable.getModel();
//                tableModel.setRowCount(0);
//                
//                // Add new content
//        for (Ingredient row : ingrediantsList) {
//            tableModel.addRow(row);
//        }
//        
//        // Update column names
//        model.setColumnIdentifiers(columnNames);
//        
//        // Notify the table that its model has changed
//        model.fireTableDataChanged();
            String[] columnNames = {"ID" , "Name" , "Expiry"};
            
            Object[][] ingrediantsObjectArray = new Object[ingrediantsList.size()][columnNames.length];
        for (int i = 0; i < ingrediantsList.size(); i++) {
            Ingredient obj = ingrediantsList.get(i);
            // Populate each row of the array with object properties
            ingrediantsObjectArray[i][0] = obj.getId();
            ingrediantsObjectArray[i][1] = obj.getName();
            ingrediantsObjectArray[i][1] = obj.getExpiryDate();
            // Add more properties as needed
        }
            
            updateTable(ingtable, ingrediantsObjectArray , columnNames);
            
            }
        } catch (ParseException e) {
            // Handle parsing error
            e.printStackTrace();
        }


 //Ingredient ing=new Ingredient(IngName.getText(),date);

//ingredientDao.addIngredient(ingredient);


    }//GEN-LAST:event_addbtnActionPerformed

    
    public static void updateTable(JTable table, Object[][] newData, String[] columnNames) {
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        
        // Clear previous content
        model.setRowCount(0);
        
        // Add new content
        for (Object[] row : newData) {
            model.addRow(row);
        }
        
        // Update column names
        model.setColumnIdentifiers(columnNames);
        
        // Notify the table that its model has changed
        model.fireTableDataChanged();
    }
    
    private void ingtableComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_ingtableComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_ingtableComponentShown

    private void delbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delbtnActionPerformed
        // TODO add your handling code here:                                       
    int selectedRow = ingtable.getSelectedRow();
    if (selectedRow != -1) {
        try {
            int id = Integer.parseInt(ingtable.getValueAt(selectedRow, 0).toString());
            ingredientDao.deleteIngredient(id);
            ((DefaultTableModel) ingtable.getModel()).removeRow(selectedRow);
            jLabel3.setText("Ingredient Deleted Successfully!!");
        } catch (Exception e) {
            jLabel3.setText("Failed to Delete Ingredient: " + e.getMessage());
        }
    } else {
        jLabel3.setText("Please select an ingredient to delete.");
    }    
    }//GEN-LAST:event_delbtnActionPerformed

    private void ingnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingnameActionPerformed
        // TODO add your handling code here:
        System.out.println("Name entered: " + ingname.getText());
    }//GEN-LAST:event_ingnameActionPerformed

    private void ingexpiryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingexpiryActionPerformed
        // TODO add your handling code here:                                         
    System.out.println("Expiry entered: " + ingexpiry.getText());
    }//GEN-LAST:event_ingexpiryActionPerformed

    private void ingtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingtableMouseClicked
        // TODO add your handling code here:
         int selectedRow = ingtable.getSelectedRow();
    if (selectedRow != -1) {
        // Assuming ID, Name, Expiry are the columns 0, 1, 2 respectively
        Object id = ingtable.getValueAt(selectedRow, 0);
        Object name = ingtable.getValueAt(selectedRow, 1);
        Object expiry = ingtable.getValueAt(selectedRow, 2);

        ingname.setText(name.toString());
        ingexpiry.setText(expiry.toString());
    }
    }//GEN-LAST:event_ingtableMouseClicked

    private void jScrollPane3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane3MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane3MouseDragged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          int a=JOptionPane.showConfirmDialog(null,"Do you really want to Close Application.","Select",JOptionPane.YES_NO_OPTION);
        if(a==0){
            System.exit(0);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FoodInventorySystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FoodInventorySystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FoodInventorySystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FoodInventorySystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FoodInventorySystem().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbtn;
    private javax.swing.JButton clearbtn;
    private javax.swing.JButton delbtn;
    private javax.swing.JFormattedTextField ingexpiry;
    private javax.swing.JTextField ingname;
    private javax.swing.JTable ingtable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton updatebtn;
    // End of variables declaration//GEN-END:variables
}
